source "https://rubygems.org"

gem "activerecord", "~> 5.2.3", :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'sqlite3'
gem 'pry'
gem 'require_all'
gem 'rack'
gem 'shotgun'
gem 'sinatra'
gem 'rest-client'

group :test do
  gem 'rack-test'
  gem 'rspec'
end